#!/bin/sh
#
# see: dh_installdeb(1)

set -e

cp -v /lib/firmware/ti-sysfw/git/*.bin /lib/firmware/ti-sysfw/

case "$1" in
	configure)
		if [ -x /usr/sbin/update-initramfs -a -e /etc/initramfs-tools/initramfs.conf ] ; then
			update-initramfs -u
		fi
	;;

	abort-upgrade|abort-remove|abort-deconfigure)
	;;

	*)
		echo "postinst called with unknown argument \`$1'" >&2
		exit 1
	;;
esac

#DEBHELPER#

exit 0

