#!/bin/sh

set -e

if [ -f /etc/systemd/timesyncd.conf ] ; then
	sed -i -e 's:#NTP=:NTP=192.168.1.12:g' /etc/systemd/timesyncd.conf
	sed -i -e 's:NTP=192.168.1.24:NTP=192.168.1.12:g' /etc/systemd/timesyncd.conf

	timedatectl
	timedatectl set-timezone America/North_Dakota/Center
	timedatectl set-ntp true
	timedatectl
fi

if [ -f /lib/systemd/system/apt-daily.service ] ; then
	systemctl disable apt-daily.service || true
	systemctl disable apt-daily.timer || true
fi

if [ -f /lib/systemd/system/apt-daily-upgrade.service ] ; then
	systemctl disable apt-daily-upgrade.service || true
	systemctl disable apt-daily-upgrade.timer || true
fi

if [ -f /etc/apt/apt.conf.d/02-no-pdiffs ] ; then
	rm -f /etc/apt/apt.conf.d/02-no-pdiffs || true
fi

if [ -f /etc/apt/apt.conf.d/02-no-languages ] ; then
	rm -f /etc/apt/apt.conf.d/02-no-languages || true
fi

if [ ! -d /mnt/farm/uptime/ ] ; then
	mkdir -p /mnt/farm || true
	echo "192.168.1.3:/var/www/html/farm /mnt/farm nfs defaults" >> /etc/fstab
fi

if [ -f /usr/lib/systemd/user/code-server.service ] ; then
	if [ -f /etc/systemd/system/multi-user.target.wants/bb-code-server.service ] ; then
		systemctl disable bb-code-server.service || true
	fi

	if [ -d /home/voodoo/ ] ; then
		systemctl enable code-server@voodoo || true
		mkdir -p  /home/voodoo/.config/code-server/ || true
		echo "bind-addr: 0.0.0.0:8080" > /home/voodoo/.config/code-server/config.yaml
		echo "auth: none" >> /home/voodoo/.config/code-server/config.yaml
		echo "cert: true" >> /home/voodoo/.config/code-server/config.yaml
		chown -R voodoo:voodoo /home/voodoo/.config/

		chown -R voodoo:voodoo /mnt/farm
	elif [ -d /home/debian/ ] ; then
		systemctl enable --now code-server@debian || true
		mkdir -p  /home/debian/.config/code-server/ || true
		echo "bind-addr: 0.0.0.0:8080" > /home/debian/.config/code-server/config.yaml
		echo "auth: none" >> /home/debian/.config/code-server/config.yaml
		echo "cert: true" >> /home/debian/.config/code-server/config.yaml
		chown -R debian:debian /home/debian/.config/

		chown -R debian:debian /mnt/farm
	fi
fi

#DEBHELPER#
