#!/bin/sh -e

if ! id | grep -q root; then
	echo "enable-beagle-flasher must be run as root:"
	echo "sudo enable-beagle-flasher"
	exit
fi

if [ -f /etc/default/beagle-flasher ] ; then
	sed -i -e 's:quiet:init=/usr/sbin/init-beagle-flasher:g' /boot/firmware/extlinux/extlinux.conf
	systemctl enable beagle-flasher-init-shutdown.service || true
else
	echo "Please setup /etc/default/beagle-flasher, for the BBB or BBAI:"
	echo "# sudo cp -v /etc/beagle-flasher/bbai64-microsd-to-emmc /etc/default/beagle-flasher"
fi
