#!/bin/bash

if ! id | grep -q root; then
	echo "beagle-pwm-export must be run as root:"
	echo "sudo beagle-pwm-export"
	exit
fi

unset GOTPIN

board=$(cat /proc/device-tree/model | awk '{print $2}'| tr -d '\000')

case "${board}" in
BeagleY-AI)
	pin_prefix="hat-"
	PWM_BUS="bus@f0000"
	;;
*)
	pin_prefix=""
	;;
esac

board_lookup () {
	board=$(cat /proc/device-tree/model | awk '{print $2}'| tr -d '\000')
	case "${board}" in
	BeagleY-AI)
		case "${PIN}" in
		gpio5|gpio14|gpio15|hat-08|hat-10|hat-29)
			PWM_ADDRESS="23000000"
			;;
		gpio6|gpio13|gpio20|hat-31|hat-33|hat-38)
			PWM_ADDRESS="23010000"
			;;
		gpio16|hat-36)
			PWM_ADDRESS="23110000"
			;;
		gpio17|gpio18|hat-11|hat-12)
			PWM_ADDRESS="23120000"
			;;
		gpio12|hat-32)
			if [ -f /proc/device-tree/chosen/overlays/${PIN}.23000000.pwm ] ; then
				PWM_ADDRESS="23000000"
			else
				PWM_ADDRESS="23100000"
			fi
			;;
		gpio21|hat-40)
			if [ -f /proc/device-tree/chosen/overlays/${PIN}.23010000.pwm ] ; then
				PWM_ADDRESS="23010000"
			else
				PWM_ADDRESS="23110000"
			fi
			;;
		*)
			echo "Unknown pin name: [--pin ${PIN}]"
			PIN_OPTIONS=$(ls /proc/device-tree/chosen/overlays/ | grep ".*\.pwm$" | awk -F"." '{print $1 "."$3}' | sed "s:pwm:pin:g" || true)
			PIN_OVERLAYS=$(ls /boot/firmware/overlays/ | grep "k3-am67a-beagley-ai-pwm.*\.dtbo$")
			echo "Possible PIN Options:"
			echo "---------------"
			echo "${PIN_OPTIONS}"
			echo "---------------"
			echo "Possible Overlay Options:"
			echo "---------------"
			echo "${PIN_OVERLAYS}"
			echo "---------------"
			exit 1
			;;
		esac
		;;
	*)
		echo "Unknown Board: [${board}]"
		exit 1
		;;
	esac
}

grab_helpers () {
	if [ ! "x${PWM_ADDRESS}" = "x" ] ; then
		PWM_EXPORT=$(cat /proc/device-tree/chosen/overlays/${PIN}.${PWM_ADDRESS}.pwm | awk -F"." '{print $3}' | tr -d '\000')
		GPIO_PI=$(cat /proc/device-tree/chosen/overlays/${PIN}.${PWM_ADDRESS}.pwm | awk -F"." '{print $4}' | tr -d '\000')
	else
		unset PWM_ADDRESS
		if [ -f /proc/device-tree/chosen/overlays/${PIN}.pin.beagle-pwm-address ] ; then
			PWM_ADDRESS=$(cat /proc/device-tree/chosen/overlays/${PIN}.pin.beagle-pwm-address | tr -d '\000')
		else
			echo "Old Overlay, missing PWM_ADDRESS upgrade overlays"
			exit 1
		fi

		unset PWM_EXPORT
		if [ -f /proc/device-tree/chosen/overlays/${PIN}.pin.beagle-pwm-export ] ; then
			PWM_EXPORT=$(cat /proc/device-tree/chosen/overlays/${PIN}.pin.beagle-pwm-export | tr -d '\000')
		else
			echo "Old Overlay, missing PWM_EXPORT upgrade overlays"
			exit 1
		fi

		unset GPIO_PI
		if [ -f /proc/device-tree/chosen/overlays/${PIN}.pin.beagle-gpio-pi ] ; then
			GPIO_PI=$(cat /proc/device-tree/chosen/overlays/${PIN}.pin.beagle-gpio-pi | tr -d '\000')
		else
			echo "Old Overlay, missing GPIO_PI upgrade overlays"
			exit 1
		fi
	fi

	if [ ! "x${GPIO_PI}" = "x" ] ; then
		if [ -d /dev/hat/pwm/${GPIO_PI}/ ] ; then
			rm -f /dev/hat/pwm/${GPIO_PI}
		fi
	fi
}

export_helpers () {
	if [ ! "x${PWM_BUS}" = "x" ] ; then
		pwmchip=$(ls /sys/devices/platform/${PWM_BUS}/${PWM_ADDRESS}.pwm/pwm/)
		if [ ! -d /sys/devices/platform/${PWM_BUS}/${PWM_ADDRESS}.pwm/pwm/${pwmchip}/pwm${PWM_EXPORT}/ ] ; then
			echo ${PWM_EXPORT} > /sys/devices/platform/${PWM_BUS}/${PWM_ADDRESS}.pwm/pwm/${pwmchip}/export
		fi

		mkdir -p /dev/hat/pwm/ || true
		ln -s /sys/devices/platform/${PWM_BUS}/${PWM_ADDRESS}.pwm/pwm/${pwmchip}/pwm${PWM_EXPORT}/ /dev/hat/pwm/${GPIO_PI}
	fi
}

checkpin () {
	if [ ! -d /proc/device-tree/chosen/overlays/ ] ; then
		echo "PWM overlay is missing, did you add it to /boot/firmware/extlinux/extlinux.conf and reboot"
		exit 1
	fi

	PIN=$(echo ${GPIN} | awk '{print tolower($0)}' || true)

	if [ "x${PIN}" = "x" ] ; then
		echo "Missing options: --pin <gpio>"
		PIN_OPTIONS=$(ls /proc/device-tree/chosen/overlays/ | grep ".*\.pwm$" | awk -F"." '{print $1 "."$3}' | sed "s:pwm:pin:g" || true)
		echo "Possible Options:"
		echo "---------------"
		echo "${PIN_OPTIONS}"
		echo "---------------"
		exit 1
	fi

	board_lookup
	if [ ! -f /proc/device-tree/chosen/overlays/${PIN}.${PWM_ADDRESS}.pwm ] ; then
		echo "Unknown pin name: [--pin ${PIN}]"
		PIN_OPTIONS=$(ls /proc/device-tree/chosen/overlays/ | grep ".*\.pwm$" | awk -F"." '{print $1 "."$3}' | sed "s:pwm:pin:g" || true)
		PIN_OVERLAYS=$(ls /boot/firmware/overlays/ | grep "k3-am67a-beagley-ai-pwm.*\.dtbo$")
		echo "Possible PIN Options:"
		echo "---------------"
		echo "${PIN_OPTIONS}"
		echo "---------------"
		echo "Possible Overlay Options:"
		echo "---------------"
		echo "${PIN_OVERLAYS}"
		echo "---------------"
		exit 1
	fi
	GOTPIN=1
}

usage () {
	echo "usage: sudo $(basename $0) --pin hat-08"
	#tabed to match 
		cat <<-__EOF__
			-----------------------------
			Required Options:
			--pin <gpio>

			Additional Options:
			        -h --help

			__EOF__
	exit
}

checkparm () {
	if [ "$(echo $1|grep ^'\-')" ] ; then
		echo "E: Need an argument"
		usage
	fi
}

# parse commandline options
while [ ! -z "$1" ] ; do
	case $1 in
	-h|--help)
		usage
		;;
	--pin)
		checkparm $2
		GPIN="$2"
		checkpin
		;;
	esac
	shift
done

if [ ${GOTPIN} ] ; then
	grab_helpers
	export_helpers
else
	usage
fi
