# Headers:
usr/include/wayland-client*
usr/include/wayland-cursor.h
usr/include/wayland-egl.h
usr/include/wayland-egl-core.h
usr/include/wayland-server*
usr/include/wayland-util.h
usr/include/wayland-version.h

# Use no wildcards to ensure we spot any update:
usr/lib/*/libwayland-client.so
usr/lib/*/libwayland-cursor.so
usr/lib/*/libwayland-egl.so
usr/lib/*/libwayland-server.so
usr/lib/*/pkgconfig/wayland-client.pc
usr/lib/*/pkgconfig/wayland-cursor.pc
usr/lib/*/pkgconfig/wayland-egl.pc
usr/lib/*/pkgconfig/wayland-server.pc

# Documentation
usr/share/wayland/wayland.xml
usr/share/wayland/wayland.dtd
