#!/bin/sh -e

version="$1"

# passing the kernel version is required
if [ -z "${version}" ] ; then
	echo >&2 "W: zz-uenv_txt: ${DPKG_MAINTSCRIPT_PACKAGE:-kernel package} did not pass a version number"
	exit 2
fi

if [ -f /boot/firmware/uEnv.txt ] ; then
	if [ -f /boot/Image ] ; then
		rm -f /boot/Image || true
		cp -v /boot/Image-${version} /boot/Image
		rm -rf /boot/*.dtb || true
		cp -v /boot/dtbs/${version}/ti/k3-j721e-*.dtb /boot/
		echo "zz-uenv_txt: Updated uEnv.txt /boot/ for: [${version}]"
	fi
fi

if [ -f /boot/firmware/extlinux/extlinux.conf ] ; then
	if [ -f /boot/Image-${version} ] ; then
		rm -f /boot/firmware/Image || true
		cp -v /boot/Image-${version} /boot/firmware/Image
		rm -rf /boot/firmware/*.dtb || true
		cp -v /boot/dtbs/${version}/ti/k3-j721e-*.dtb /boot/firmware/
		echo "zz-uenv_txt: Updated extlinux.conf /boot/firmware/ for: [${version}]"
	fi
fi
