#!/bin/sh

set -e

groupadd gpio --system || true

check_n_ln () {
	if [ ! -f /lib/firmware/${wfirm} ] ; then
		ln -sf /lib/firmware/${wfirm}.tisdk /lib/firmware/${wfirm}
		/bin/chgrp gpio /lib/firmware/${wfirm}
		/bin/chmod g=u /lib/firmware/${wfirm}
	fi
}

wfirm="j7-c66_0-fw" ; check_n_ln
wfirm="j7-c66_1-fw" ; check_n_ln
wfirm="j7-c71_0-fw" ; check_n_ln
wfirm="j7-main-r5f0_0-fw" ; check_n_ln
wfirm="j7-main-r5f0_1-fw" ; check_n_ln
wfirm="j7-main-r5f1_0-fw" ; check_n_ln
wfirm="j7-main-r5f1_1-fw" ; check_n_ln
wfirm="j7-mcu-r5f0_0-fw" ; check_n_ln
wfirm="j7-mcu-r5f0_1-fw" ; check_n_ln

case "$1" in
	configure)
		if [ -x /usr/sbin/update-initramfs -a -e /etc/initramfs-tools/initramfs.conf ] ; then
			update-initramfs -u
		fi
	;;

	abort-upgrade|abort-remove|abort-deconfigure)
	;;

	*)
		echo "postinst called with unknown argument \`$1'" 1>&2
		exit 1
	;;
esac

#DEBHELPER#
