#!/bin/sh

set -e

groupadd gpio --system || true

if [ ! -f /lib/firmware/j7-c66_0-fw ] ; then
	ln -sf /lib/firmware/j7-c66_0-fw.tisdk /lib/firmware/j7-c66_0-fw
	/bin/chgrp gpio /lib/firmware/j7-c66_0-fw
	/bin/chmod g=u /lib/firmware/j7-c66_0-fw
fi
if [ ! -f /lib/firmware/j7-c66_1-fw ] ; then
	ln -sf /lib/firmware/j7-c66_1-fw.tisdk /lib/firmware/j7-c66_1-fw
	/bin/chgrp gpio /lib/firmware/j7-c66_1-fw
	/bin/chmod g=u /lib/firmware/j7-c66_1-fw
fi
if [ ! -f /lib/firmware/j7-c71_0-fw ] ; then
	ln -sf /lib/firmware/j7-c71_0-fw.tisdk /lib/firmware/j7-c71_0-fw
	/bin/chgrp gpio /lib/firmware/j7-c71_0-fw
	/bin/chmod g=u /lib/firmware/j7-c71_0-fw
fi
if [ ! -f /lib/firmware/j7-main-r5f0_0-fw ] ; then
	ln -sf /lib/firmware/j7-main-r5f0_0-fw.tisdk /lib/firmware/j7-main-r5f0_0-fw
	/bin/chgrp gpio /lib/firmware/j7-main-r5f0_0-fw
	/bin/chmod g=u /lib/firmware/j7-main-r5f0_0-fw
fi
if [ ! -f /lib/firmware/j7-main-r5f0_1-fw ] ; then
	ln -sf /lib/firmware/j7-main-r5f0_1-fw.tisdk /lib/firmware/j7-main-r5f0_1-fw
	/bin/chgrp gpio /lib/firmware/j7-main-r5f0_1-fw
	/bin/chmod g=u /lib/firmware/j7-main-r5f0_1-fw
fi
if [ ! -f /lib/firmware/j7-main-r5f1_0-fw ] ; then
	ln -sf /lib/firmware/j7-main-r5f1_0-fw.tisdk /lib/firmware/j7-main-r5f1_0-fw
	/bin/chgrp gpio /lib/firmware/j7-main-r5f1_0-fw
	/bin/chmod g=u /lib/firmware/j7-main-r5f1_0-fw
fi
if [ -f /lib/firmware/j7-main-r5f1_1-fw ] ; then
	ln -sf /lib/firmware/j7-main-r5f1_1-fw.tisdk /lib/firmware/j7-main-r5f1_1-fw
	/bin/chgrp gpio /lib/firmware/j7-main-r5f1_1-fw
	/bin/chmod g=u /lib/firmware/j7-main-r5f1_1-fw
fi

case "$1" in
	configure)
		if [ -x /usr/sbin/update-initramfs -a -e /etc/initramfs-tools/initramfs.conf ] ; then
			update-initramfs -u
		fi
	;;

	abort-upgrade|abort-remove|abort-deconfigure)
	;;

	*)
		echo "postinst called with unknown argument \`$1'" 1>&2
		exit 1
	;;
esac

#DEBHELPER#
