#!/bin/bash

log="bb-start-vision-apps-eaik-8-2"

APP_core0="vision_apps_eaik_8.2/vx_app_rtos_linux_mcu2_0.out"
APP_core1="vision_apps_eaik_8.2/vx_app_rtos_linux_mcu2_1.out"

core0=$(ls /sys/devices/platform/bus@100000/bus@100000:r5fss@5c00000/5c00000.r5f/remoteproc/ | grep remoteproc || true)
core1=$(ls /sys/devices/platform/bus@100000/bus@100000:r5fss@5c00000/5d00000.r5f/remoteproc/ | grep remoteproc || true)

echo ${core0}
echo stop > /sys/class/remoteproc/${core0}/state || true
echo ${APP_core0} > /sys/class/remoteproc/${core0}/firmware
echo start > /sys/class/remoteproc/${core0}/state

echo ${core1}
echo stop > /sys/class/remoteproc/${core1}/state || true
echo ${APP_core1} > /sys/class/remoteproc/${core1}/firmware
echo start > /sys/class/remoteproc/${core1}/state
