#!/bin/bash

if ! id | grep -q root; then
	echo "beagle-pin-mux must be run as root:"
	echo "sudo beagle-pin-mux"
	exit
fi

unset GOTPIN
unset GOTMODE

board=$(cat /proc/device-tree/model | awk '{print $2}'| tr -d '\000')

case "${board}" in
BeagleY-AI)
	pin_prefix="hat-"
	;;
*)
	pin_prefix=""
	;;
esac

grab_helpers () {
	unset PWM_BUS
	if [ -f /sys/firmware/devicetree/base/${PIN}-${MODE}/beagle-pwm-bus ] ; then
		PWM_BUS=$(cat /sys/firmware/devicetree/base/${PIN}-${MODE}/beagle-pwm-bus | tr -d '\000')
	fi

	unset PWM_ADDRESS
	if [ -f /sys/firmware/devicetree/base/${PIN}-${MODE}/beagle-pwm-address ] ; then
		PWM_ADDRESS=$(cat /sys/firmware/devicetree/base/${PIN}-${MODE}/beagle-pwm-address | tr -d '\000')
	fi

	unset PWM_EXPORT
	if [ -f /sys/firmware/devicetree/base/${PIN}-${MODE}/beagle-pwm-export ] ; then
		PWM_EXPORT=$(cat /sys/firmware/devicetree/base/${PIN}-${MODE}/beagle-pwm-export | tr -d '\000')
	fi

	unset GPIO_PI
	if [ -f /sys/firmware/devicetree/base/${PIN}-${MODE}/beagle-gpio-pi ] ; then
		GPIO_PI=$(cat /sys/firmware/devicetree/base/${PIN}-${MODE}/beagle-gpio-pi | tr -d '\000')
	fi
}

export_helpers () {
	if [ ! "x${PWM_BUS}" = "x" ] ; then
		pwmchip=$(ls /sys/devices/platform/${PWM_BUS}/${PWM_ADDRESS}.pwm/pwm/)
		if [ ! -d /sys/devices/platform/${PWM_BUS}/${PWM_ADDRESS}.pwm/pwm/${pwmchip}/pwm${PWM_EXPORT}/ ] ; then
			echo ${PWM_EXPORT} > /sys/devices/platform/${PWM_BUS}/${PWM_ADDRESS}.pwm/pwm/${pwmchip}/export
		fi

		mkdir -p /dev/hat/pwm/ || true
		ln -s /sys/devices/platform/${PWM_BUS}/${PWM_ADDRESS}.pwm/pwm/${pwmchip}/pwm${PWM_EXPORT}/ /dev/hat/pwm/${GPIO_PI}
	fi
}

driver_override () {
	if [ ! -f /sys/devices/platform/${PIN}-${MODE}/driver_override ] ; then
		echo "Missing driver_override: ${PIN}-${MODE}"
		exit 1
	else
		grab_helpers
		if [ -d /dev/hat/pwm/${PIN}/ ] ; then
			rm -f /dev/hat/pwm/${PIN}
		fi
		if [ -d /dev/hat/pwm/${PIN}-pwm/ ] ; then
			rm -f /dev/hat/pwm/${PIN}-pwm
		fi
		if [ -d /dev/hat/pwm/${PIN}-pwm-ecap/ ] ; then
			rm -f /dev/hat/pwm/${PIN}-pwm-ecap
		fi
		if [ ! "x${GPIO_PI}" = "x" ] ; then
			if [ -d /dev/hat/pwm/${GPIO_PI}/ ] ; then
				rm -f /dev/hat/pwm/${GPIO_PI}
			fi
		fi
		echo gpio-aggregator > /sys/devices/platform/${PIN}-${MODE}/driver_override
	fi
}

bind_driver () {
	if [ ! -f /sys/bus/platform/drivers/gpio-aggregator/bind ] ; then
		echo "Missing gpio-aggregator: ${PIN}-${MODE}"
		exit 1
	else
		echo ${PIN}-${MODE} > /sys/bus/platform/drivers/gpio-aggregator/bind
		export_helpers
	fi
}

checkpin () {
	if [ "x${PIN}" = "x" ] ; then
		echo "Missing options: --pin <gpio>"
		PIN_OPTIONS=$(ls /sys/devices/platform/ | grep gpio-pu | grep ${pin_prefix} | awk -F '-gpio' '{print $1}')
		echo "Possible Options:"
		echo "---------------"
		echo "${PIN_OPTIONS}"
		echo "---------------"
		exit 1
	fi
	if [ ! -f /proc/device-tree/chosen/overlays/${PIN}.pin ] ; then
		if [ ! -d /sys/devices/platform/${PIN}-gpio ] ; then
			echo "Unknown pin name: [--pin ${PIN}]"
			PIN_OPTIONS=$(ls /sys/devices/platform/ | grep gpio-pu | grep ${pin_prefix} | awk -F '-gpio' '{print $1}')
			echo "Possible Options:"
			echo "---------------"
			echo "${PIN_OPTIONS}"
			echo "---------------"
			exit 1
		fi
		pinloaded=$(ls /sys/bus/platform/drivers/gpio-aggregator/ | grep ${PIN})
		if [ ! "x${pinloaded}" = "x" ] ; then
			echo ${pinloaded} > /sys/bus/platform/drivers/gpio-aggregator/unbind
		fi
		GOTPIN=1
	else
		loaded_overlay=$(cat /proc/device-tree/chosen/overlays/${PIN}.pin | tr -d '\000')
		echo "PIN: [${PIN}] is already taken by overlay [${loaded_overlay}.dtbo]"
		echo "USE: [sudo beagle-pwm-export --pin ${PIN}] to set the pwm symlink"
		exit 1
	fi
}

checkpinmode () {
	if [ "x${MODE}" = "x" ] ; then
		echo "Missing paramater: --mode <mode>"
		MODES=$(ls /sys/devices/platform/ | grep ${PIN} | awk -F ${PIN}- '{print $2}')
		echo "Possible Options:"
		echo "---------------"
		echo "${MODES}"
		echo "---------------"
		exit 1
	fi
	if [ ! -d /sys/devices/platform/${PIN}-${MODE} ] ; then
		echo "Unknown --pin/--mode combination: [--pin ${PIN} --mode ${MODE}]:"
		MODES=$(ls /sys/devices/platform/ | grep ${PIN} | awk -F ${PIN}- '{print $2}')
		echo "Possible Options:"
		echo "---------------"
		echo "${MODES}"
		echo "---------------"
		exit 1
	fi
	GOTMODE=1
}

usage () {
	echo "usage: sudo $(basename $0) --pin hat-08 --mode gpio"
	#tabed to match 
		cat <<-__EOF__
			-----------------------------
			Required Options:
			--pin <gpio>

			--mode <mode>

			Additional Options:
			        -h --help

			__EOF__
	exit
}

checkparm () {
	if [ "$(echo $1|grep ^'\-')" ] ; then
		echo "E: Need an argument"
		usage
	fi
}

# parse commandline options
while [ ! -z "$1" ] ; do
	case $1 in
	-h|--help)
		usage
		;;
	--pin)
		checkparm $2
		PIN="$2"
		checkpin
		;;
	--mode)
		checkparm $2
		MODE="$2"
		checkpinmode
		;;
	esac
	shift
done

if [ ${GOTPIN} ] && [ ${GOTMODE} ] ; then
	driver_override
	bind_driver
else
	usage
fi
