#!/bin/sh

set -e

if [ -f /etc/default/generic-sys-mods ] ; then
	. /etc/default/generic-sys-mods
else
	ROOT_DRIVE="/dev/mmcblk1"
	ROOT_PARTITION="2"
fi

echo "#This file is sourced by /usb/bin/bb-growpart" > /etc/default/generic-sys-mods
echo "ROOT_DRIVE=${ROOT_DRIVE}" >> /etc/default/generic-sys-mods
echo "ROOT_PARTITION=${ROOT_PARTITION}" >> /etc/default/generic-sys-mods

chmod +x /etc/kernel/postinst.d/zz-uenv_txt || true

cp -vf /etc/bbb.io/templates/profile /etc/profile

#DEBHELPER#
