#!/bin/sh -e

version="$1"

# passing the kernel version is required
if [ -z "${version}" ] ; then
	echo >&2 "W: zz-uenv_txt: ${DPKG_MAINTSCRIPT_PACKAGE:-kernel package} did not pass a version number"
	exit 2
fi

if [ -f /boot/firmware/extlinux/extlinux.conf ] ; then
	if [ -f /boot/vmlinuz-${version} ] ; then
		if [ ! -d /boot/firmware/ti/ ] ; then
			mkdir -p /boot/firmware/ti/ || true
		fi
		if [ ! -d /boot/firmware/overlays/ ] ; then
			mkdir -p /boot/firmware/overlays/ || true
		fi

		echo "Updating: Device Trees"
		cp /usr/lib/linux-image-${version}/ti/k3-*.dtb /boot/firmware/ti/ || true
		echo "Updating: Device Tree Overlays"
		cp /usr/lib/linux-image-${version}/ti/*.dtbo /boot/firmware/overlays/ || true

		if [ -f /boot/firmware/Image ] ; then
			rm -f /boot/firmware/Image || true
			echo "Updating: /boot/firmware/Image"
			cat /boot/vmlinuz-${version} | gunzip -d > /boot/firmware/Image
		fi

		rm -f /boot/firmware/Image.gz || true
		echo "Updating: /boot/firmware/Image.gz"
		cp -v /boot/vmlinuz-${version} /boot/firmware/Image.gz

		rm -f /boot/firmware/initrd.img || true
		echo "Updating: /boot/firmware/initrd.img"
		cp /boot/initrd.img-${version} /boot/firmware/initrd.img || true
		if [ -d /usr/lib/linux-image-${version}/ti/overlays/ ] ; then
			cp /usr/lib/linux-image-${version}/ti/overlays/*.dtbo /boot/firmware/overlays/ || true
		fi
		echo "${version}" > /boot/firmware/kversion
		echo "zz-uenv_txt: Updated extlinux.conf /boot/firmware/ for: [${version}]"
	fi
fi
