#!/bin/sh -e

version="$1"

# passing the kernel version is required
if [ -z "${version}" ] ; then
	echo >&2 "W: zz-uenv_txt: ${DPKG_MAINTSCRIPT_PACKAGE:-kernel package} did not pass a version number"
	exit 2
fi

if [ -f /boot/firmware/uEnv.txt ] ; then
	if [ -f /boot/Image ] ; then
		rm -f /boot/Image || true
		cp -v /boot/Image-${version} /boot/Image
		rm -rf /boot/*.dtb || true
		cp -v /boot/dtbs/${version}/ti/k3-j721e-*.dtb /boot/
		echo "zz-uenv_txt: Updated uEnv.txt /boot/ for: [${version}]"
	fi
fi

if [ -f /boot/firmware/extlinux/extlinux.conf ] ; then
	if [ -f /boot/vmlinuz-${version} ] ; then
		mkdir -p /boot/firmware/ti/ || true
		echo "Updating: Device Trees"
		cp /usr/lib/linux-image-${version}/ti/k3-*.dtb /boot/firmware/ti/ || true

		rm -f /boot/firmware/Image || true
		echo "Updating: /boot/firmware/Image"
		cat /boot/vmlinuz-${version} | gunzip -d > /boot/firmware/Image

		rm -f /boot/firmware/initrd.img || true
		echo "Updating: /boot/firmware/initrd.img"
		cp -v /boot/initrd.img-${version} /boot/firmware/initrd.img || true
		if [ -d /usr/lib/linux-image-${version}/ti/overlays/ ] ; then
			mkdir -p /boot/firmware/overlays/ || true
			echo "Updating: overlays"
			cp /usr/lib/linux-image-${version}/ti/overlays/*.dtbo /boot/firmware/overlays/ || true
		fi
		echo "${version}" > /boot/firmware/kversion
		echo "zz-uenv_txt: Updated extlinux.conf /boot/firmware/ for: [${version}]"
	fi
fi
