title: "RPi Camera Demo"
log_level: 2
inputs:
    # rpi camera is supported only in Starter Kit
    # rpiV2 camera should be connected to CAM1 rpi header on SK
    # k3-j721e-sk-rpi-cam-imx219.dtbo should be applied in uenv.txt
    input0:
        source: /dev/video2
        width: 1920
        height: 1080
        format: rggb
        subdev-id: 2
        framerate: 30
models:
    model0:
        model_path: /opt/model_zoo/TVM-CL-3410-gluoncv-mxnet-mobv2
        topN: 5
    model1:
        model_path: /opt/model_zoo/ONR-OD-8050-ssd-lite-regNetX-800mf-fpn-bgr-mmdet-coco-512x512
        viz_threshold: 0.6
    model2:
        model_path: /opt/model_zoo/ONR-SS-8610-deeplabv3lite-mobv2-ade20k32-512x512
        alpha: 0.4
outputs:
    output0:
        sink: kmssink
        width: 1920
        height: 1080
    output1:
        sink: /opt/edge_ai_apps/data/output/videos/output_video.mkv
        width: 1920
        height: 1080
    output2:
        sink: /opt/edge_ai_apps/data/output/images/output_image_%04d.jpg
        width: 1920
        height: 1080

flows:
    flow0:
        input: input0
        models: [model1]
        outputs: [output0]
        mosaic:
            mosaic0:
                width:  1280
                height: 720
                pos_x:  320
                pos_y:  180
