Section "Device"
    Identifier "Card0"
    Driver     "modesetting"
    Option     "AccelMethod" "none"
#    Option     "AccelMethod"  "glamor"
##    Option     "RenderingAPI" "gl"
#    Option     "RenderingAPI" "es"
EndSection
