#!/bin/bash -e

. version.sh

current_kernel () {
	if [ -f /tmp/LATEST-${var} ] ; then
		rm -rf /tmp/LATEST-${var} | true
	fi
	wget --quiet --directory-prefix=/tmp/ https://rcn-ee.net/repos/latest/${dist}-${arch}/LATEST-${var}
	unset latest_kernel
	latest_kernel=$(cat "/tmp/LATEST-${var}" | grep "ABI:1 ${ver}" | awk '{print $3}')
}

generate_header () {
	echo "# This file is autogenerated. Do not edit!" > ./suite/${dist}/debian/${wfile}
	echo "Source: bbb.io-kernel" >> ./suite/${dist}/debian/${wfile}
	echo "Section: misc" >> ./suite/${dist}/debian/${wfile}
	echo "Priority: optional" >> ./suite/${dist}/debian/${wfile}
	echo "Maintainer: Robert Nelson <robertcnelson@gmail.com>" >> ./suite/${dist}/debian/${wfile}
	echo "Build-Depends:" >> ./suite/${dist}/debian/${wfile}
	echo " debhelper-compat (= ${debhelper})" >> ./suite/${dist}/debian/${wfile}
	echo "Standards-Version: 4.5.0" >> ./suite/${dist}/debian/${wfile}
	echo "Rules-Requires-Root: no" >> ./suite/${dist}/debian/${wfile}
	echo "" >> ./suite/${dist}/debian/${wfile}
	echo "Package: bbb.io-kernel-tasks" >> ./suite/${dist}/debian/${wfile}
	echo "Architecture: arm64" >> ./suite/${dist}/debian/${wfile}
	echo "Pre-Depends:" >> ./suite/${dist}/debian/${wfile}
	echo " bb-j721e-evm-firmware" >> ./suite/${dist}/debian/${wfile}
	echo " , generic-sys-mods" >> ./suite/${dist}/debian/${wfile}
	echo "Depends:" >> ./suite/${dist}/debian/${wfile}
	echo " tasksel" >> ./suite/${dist}/debian/${wfile}
	echo " , generic-sys-mods" >> ./suite/${dist}/debian/${wfile}
	echo " , \${misc:Depends}" >> ./suite/${dist}/debian/${wfile}
	echo "Description: BeagleBoard.org Kernel Branches" >> ./suite/${dist}/debian/${wfile}
	echo " This package contains tasksel information for the BeagleBoard.org Kernel Branch." >> ./suite/${dist}/debian/${wfile}
}

generate_kernel_ti () {
	echo "" >> ./suite/${dist}/debian/${wfile}
	echo "Package: bbb.io-kernel-${msg}" >> ./suite/${dist}/debian/${wfile}
	echo "Section: metapackages" >> ./suite/${dist}/debian/${wfile}
	echo "Architecture: arm64" >> ./suite/${dist}/debian/${wfile}
	echo "Pre-Depends:" >> ./suite/${dist}/debian/${wfile}
	echo " bb-j721e-evm-firmware" >> ./suite/${dist}/debian/${wfile}
	echo " , generic-sys-mods" >> ./suite/${dist}/debian/${wfile}
	echo " , linux-image-${latest_kernel}" >> ./suite/${dist}/debian/${wfile}
	echo "Depends: \${misc:Depends}, bbb.io-kernel-tasks (= \${source:Version})" >> ./suite/${dist}/debian/${wfile}
	echo "Description: BeagleBoard.org ${msg}" >> ./suite/${dist}/debian/${wfile}
	echo " This metapackage will install linux-image-${msg} in Debian." >> ./suite/${dist}/debian/${wfile}

	echo "" >> ./suite/${dist}/debian/${wfile}
	echo "Package: bbb.io-kernel-${msg}-k3-am62" >> ./suite/${dist}/debian/${wfile}
	echo "Section: metapackages" >> ./suite/${dist}/debian/${wfile}
	echo "Architecture: arm64" >> ./suite/${dist}/debian/${wfile}
	echo "Pre-Depends:" >> ./suite/${dist}/debian/${wfile}
	echo " bbb.io-kernel-${msg}" >> ./suite/${dist}/debian/${wfile}
	echo "Depends: \${misc:Depends}, bbb.io-kernel-tasks (= \${source:Version})" >> ./suite/${dist}/debian/${wfile}
	echo "Recommends:" >> ./suite/${dist}/debian/${wfile}
	echo " bb-u-boot-beagleplay" >> ./suite/${dist}/debian/${wfile}
	if [ "x${sgxam62}" = "xenabled" ] ; then
		echo " , ti-${sgxmodule}-am62-modules-${latest_kernel}" >> ./suite/${dist}/debian/${wfile}
	fi
	echo "Description: BeagleBoard.org ${msg}" >> ./suite/${dist}/debian/${wfile}
	echo " This metapackage will install linux-image-${msg} for k3-am62 in Debian." >> ./suite/${dist}/debian/${wfile}

	echo "" >> ./suite/${dist}/debian/${wfile}
	echo "Package: bbb.io-kernel-${msg}-k3-j721e" >> ./suite/${dist}/debian/${wfile}
	echo "Section: metapackages" >> ./suite/${dist}/debian/${wfile}
	echo "Architecture: arm64" >> ./suite/${dist}/debian/${wfile}
	echo "Pre-Depends:" >> ./suite/${dist}/debian/${wfile}
	echo " bbb.io-kernel-${msg}" >> ./suite/${dist}/debian/${wfile}
	echo "Depends: \${misc:Depends}, bbb.io-kernel-tasks (= \${source:Version})" >> ./suite/${dist}/debian/${wfile}
	echo "Recommends:" >> ./suite/${dist}/debian/${wfile}
	echo " bb-u-boot-beagleboneai64" >> ./suite/${dist}/debian/${wfile}
	if [ "x${sgxj721e}" = "xenabled" ] ; then
		echo " , ti-${sgxmodule}-j721e-modules-${latest_kernel}" >> ./suite/${dist}/debian/${wfile}
	fi
	echo "Description: BeagleBoard.org ${msg}" >> ./suite/${dist}/debian/${wfile}
	echo " This metapackage will install linux-image-${msg} for k3-j721e in Debian." >> ./suite/${dist}/debian/${wfile}
}

generate_mainline_kernel () {
	echo "" >> ./suite/${dist}/debian/${wfile}
	echo "Package: bbb.io-kernel-${msg}" >> ./suite/${dist}/debian/${wfile}
	echo "Section: metapackages" >> ./suite/${dist}/debian/${wfile}
	echo "Architecture: arm64" >> ./suite/${dist}/debian/${wfile}
	echo "Pre-Depends: linux-image-${latest_kernel}" >> ./suite/${dist}/debian/${wfile}
	echo "Depends: \${misc:Depends}, bbb.io-kernel-tasks (= \${source:Version})" >> ./suite/${dist}/debian/${wfile}
	echo "Description: BeagleBoard.org Mainline" >> ./suite/${dist}/debian/${wfile}
	echo " This metapackage will install Mainline in Debian." >> ./suite/${dist}/debian/${wfile}
}

generate_kernel_k3 () {
	echo "" >> ./suite/${dist}/debian/${wfile}
	echo "Package: bbb.io-kernel-${msg}" >> ./suite/${dist}/debian/${wfile}
	echo "Section: metapackages" >> ./suite/${dist}/debian/${wfile}
	echo "Architecture: arm64" >> ./suite/${dist}/debian/${wfile}
	echo "Pre-Depends: linux-image-${latest_kernel}" >> ./suite/${dist}/debian/${wfile}
	echo "Depends: \${misc:Depends}, bbb.io-kernel-tasks (= \${source:Version})" >> ./suite/${dist}/debian/${wfile}
	echo "Description: BeagleBoard.org ${msg}-arm64 for k3-arm64" >> ./suite/${dist}/debian/${wfile}
	echo " This metapackage will install linux-image-${msg}-arm64 for in Debian." >> ./suite/${dist}/debian/${wfile}
}

do_bullseye () {
	arch="arm64"
	dist="bullseye"
	debhelper="13"
	wfile="control"
	generate_header

	sgxam62="enabled"
	sgxj721e="enabled"
	sgxmodule="sgx"

	msg="5.10-ti"   ; var="ti-arm64" ; ver="LTS510"  ; current_kernel ; generate_kernel_ti
	msg="mainline"  ; var="arm64"    ; ver="STABLE"  ; current_kernel ; generate_mainline_kernel
	msg="6.3-k3"    ; var="k3-arm64"    ; ver="V63X" ; current_kernel ; generate_kernel_k3
	msg="6.3-rt-k3" ; var="k3-arm64-rt" ; ver="V63X" ; current_kernel ; generate_kernel_k3
}

do_bookworm () {
	arch="arm64"
	dist="bookworm"
	debhelper="13"
	wfile="control"
	generate_header

	sgxam62="enabled"
	sgxj721e="enabled"
	sgxmodule="sgx-1.18"

	msg="5.10-ti"   ; var="ti-arm64" ; ver="LTS510"  ; current_kernel ; generate_kernel_ti
	msg="mainline"  ; var="arm64"    ; ver="STABLE"  ; current_kernel ; generate_mainline_kernel
	msg="6.3-k3"    ; var="k3-arm64"    ; ver="V63X" ; current_kernel ; generate_kernel_k3
	msg="6.3-rt-k3" ; var="k3-arm64-rt" ; ver="V63X" ; current_kernel ; generate_kernel_k3
}

do_bullseye
do_bookworm

