#!/bin/bash -e

. version.sh

current_kernel () {
	if [ -f /tmp/LATEST-${var} ] ; then
		rm -rf /tmp/LATEST-${var} | true
	fi
	unset latest_kernel
	wget --quiet --directory-prefix=/tmp/ https://rcn-ee.us/repos/latest/${dist}-${arch}/LATEST-${var} || true
	if [ -f /tmp/LATEST-${var} ] ; then
		latest_kernel=$(cat "/tmp/LATEST-${var}" | grep "ABI:1 ${ver}" | awk '{print $3}')
		echo ${dist}-${arch}-${latest_kernel}
	fi
}

generate_header () {
	echo "# This file is autogenerated. Do not edit!" > ./suite/${dist}/debian/${wfile}
	echo "Source: bbb.io-kernel" >> ./suite/${dist}/debian/${wfile}
	echo "Section: misc" >> ./suite/${dist}/debian/${wfile}
	echo "Priority: optional" >> ./suite/${dist}/debian/${wfile}
	echo "Maintainer: Robert Nelson <robertcnelson@gmail.com>" >> ./suite/${dist}/debian/${wfile}
	echo "Build-Depends:" >> ./suite/${dist}/debian/${wfile}
	echo " debhelper-compat (= ${debhelper})" >> ./suite/${dist}/debian/${wfile}
	echo "Standards-Version: 4.5.0" >> ./suite/${dist}/debian/${wfile}
	echo "Rules-Requires-Root: no" >> ./suite/${dist}/debian/${wfile}
	echo "" >> ./suite/${dist}/debian/${wfile}
	echo "Package: bbb.io-kernel-tasks" >> ./suite/${dist}/debian/${wfile}
	echo "Architecture: arm64" >> ./suite/${dist}/debian/${wfile}
	echo "Pre-Depends:" >> ./suite/${dist}/debian/${wfile}
	echo " bb-j721e-evm-firmware" >> ./suite/${dist}/debian/${wfile}
	echo " , bbb.io-clickid-manifests" >> ./suite/${dist}/debian/${wfile}
	echo " , generic-sys-mods" >> ./suite/${dist}/debian/${wfile}
	echo " , ti-linux-firmware-sysfw" >> ./suite/${dist}/debian/${wfile}
	echo "Depends:" >> ./suite/${dist}/debian/${wfile}
	echo " tasksel" >> ./suite/${dist}/debian/${wfile}
	echo " , \${misc:Depends}" >> ./suite/${dist}/debian/${wfile}
	echo "Description: BeagleBoard.org Kernel Branches" >> ./suite/${dist}/debian/${wfile}
	echo " This package contains tasksel information for the BeagleBoard.org Kernel Branch." >> ./suite/${dist}/debian/${wfile}
}

generate_kernel_ti () {
	if [ ! "x${latest_kernel}" = "x" ] ; then
		echo "" >> ./suite/${dist}/debian/${wfile}
		echo "Package: bbb.io-kernel-${msg}" >> ./suite/${dist}/debian/${wfile}
		echo "Section: metapackages" >> ./suite/${dist}/debian/${wfile}
		echo "Architecture: arm64" >> ./suite/${dist}/debian/${wfile}
		echo "Pre-Depends: linux-image-${latest_kernel}" >> ./suite/${dist}/debian/${wfile}
		echo "Depends: \${misc:Depends}, bbb.io-kernel-tasks (= \${source:Version})" >> ./suite/${dist}/debian/${wfile}
		echo "Description: BeagleBoard.org ${msg}" >> ./suite/${dist}/debian/${wfile}
		echo " This metapackage will install linux-image-${msg} in Debian." >> ./suite/${dist}/debian/${wfile}

		echo "" >> ./suite/${dist}/debian/${wfile}
		echo "Package: bbb.io-kernel-${msg}-k3-am62" >> ./suite/${dist}/debian/${wfile}
		echo "Section: metapackages" >> ./suite/${dist}/debian/${wfile}
		echo "Architecture: arm64" >> ./suite/${dist}/debian/${wfile}
		echo "Pre-Depends:" >> ./suite/${dist}/debian/${wfile}
		echo " bbb.io-kernel-${msg}" >> ./suite/${dist}/debian/${wfile}
		echo "Depends: \${misc:Depends}, bbb.io-kernel-tasks (= \${source:Version})" >> ./suite/${dist}/debian/${wfile}
		echo "Recommends:" >> ./suite/${dist}/debian/${wfile}
		echo " bb-u-boot-beagleplay" >> ./suite/${dist}/debian/${wfile}
		if [ "x${sgxam62}" = "xenabled" ] ; then
			echo " , ti-${sgxmodule}-am62-modules-${latest_kernel}" >> ./suite/${dist}/debian/${wfile}
		fi
		echo "Description: BeagleBoard.org ${msg}" >> ./suite/${dist}/debian/${wfile}
		echo " This metapackage will install linux-image-${msg} for k3-am62 in Debian." >> ./suite/${dist}/debian/${wfile}

		if [ "x${am62_dev}" = "xenabled" ] ; then
			echo "" >> ./suite/${dist}/debian/${wfile}
			echo "Package: bbb.io-kernel-${msg}-k3-am62-developer" >> ./suite/${dist}/debian/${wfile}
			echo "Section: metapackages" >> ./suite/${dist}/debian/${wfile}
			echo "Architecture: arm64" >> ./suite/${dist}/debian/${wfile}
			echo "Pre-Depends:" >> ./suite/${dist}/debian/${wfile}
			echo " bbb.io-kernel-${msg}-k3-am62" >> ./suite/${dist}/debian/${wfile}
			echo "Depends: \${misc:Depends}, bbb.io-kernel-tasks (= \${source:Version})" >> ./suite/${dist}/debian/${wfile}
			echo "Recommends:" >> ./suite/${dist}/debian/${wfile}
			echo " bb-u-boot-beagleplay" >> ./suite/${dist}/debian/${wfile}
			echo " , bb-u-boot-beagleplay-ti-2023.04" >> ./suite/${dist}/debian/${wfile}
			echo " , bb-u-boot-beagleplay-mainline" >> ./suite/${dist}/debian/${wfile}
			echo "Description: BeagleBoard.org ${msg}" >> ./suite/${dist}/debian/${wfile}
			echo " This metapackage will install linux-image-${msg} for k3-am62 developer in Debian." >> ./suite/${dist}/debian/${wfile}
		fi

		echo "" >> ./suite/${dist}/debian/${wfile}
		echo "Package: bbb.io-kernel-${msg}-k3-j721e" >> ./suite/${dist}/debian/${wfile}
		echo "Section: metapackages" >> ./suite/${dist}/debian/${wfile}
		echo "Architecture: arm64" >> ./suite/${dist}/debian/${wfile}
		echo "Pre-Depends:" >> ./suite/${dist}/debian/${wfile}
		echo " bbb.io-kernel-${msg}" >> ./suite/${dist}/debian/${wfile}
		echo "Depends: \${misc:Depends}, bbb.io-kernel-tasks (= \${source:Version})" >> ./suite/${dist}/debian/${wfile}
		echo "Recommends:" >> ./suite/${dist}/debian/${wfile}
		echo " bb-u-boot-beagleboneai64" >> ./suite/${dist}/debian/${wfile}
		if [ "x${sgxj721e}" = "xenabled" ] ; then
			echo " , ti-${sgxmodule}-j721e-modules-${latest_kernel}" >> ./suite/${dist}/debian/${wfile}
		fi
		echo "Description: BeagleBoard.org ${msg}" >> ./suite/${dist}/debian/${wfile}
		echo " This metapackage will install linux-image-${msg} for k3-j721e in Debian." >> ./suite/${dist}/debian/${wfile}

		if [ "x${j721e_dev}" = "xenabled" ] ; then
			echo "" >> ./suite/${dist}/debian/${wfile}
			echo "Package: bbb.io-kernel-${msg}-k3-j721e-developer" >> ./suite/${dist}/debian/${wfile}
			echo "Section: metapackages" >> ./suite/${dist}/debian/${wfile}
			echo "Architecture: arm64" >> ./suite/${dist}/debian/${wfile}
			echo "Pre-Depends:" >> ./suite/${dist}/debian/${wfile}
			echo " bbb.io-kernel-${msg}-k3-j721e" >> ./suite/${dist}/debian/${wfile}
			echo "Depends: \${misc:Depends}, bbb.io-kernel-tasks (= \${source:Version})" >> ./suite/${dist}/debian/${wfile}
			echo "Recommends:" >> ./suite/${dist}/debian/${wfile}
			echo " bb-u-boot-beagleboneai64" >> ./suite/${dist}/debian/${wfile}
			echo " , bb-u-boot-beagleboneai64-ti-2023.04" >> ./suite/${dist}/debian/${wfile}
			echo "Description: BeagleBoard.org ${msg}" >> ./suite/${dist}/debian/${wfile}
			echo " This metapackage will install linux-image-${msg} for k3-j721e developer in Debian." >> ./suite/${dist}/debian/${wfile}
		fi
	fi
}

generate_mainline_kernel () {
	if [ ! "x${latest_kernel}" = "x" ] ; then
		echo "" >> ./suite/${dist}/debian/${wfile}
		echo "Package: bbb.io-kernel-${msg}" >> ./suite/${dist}/debian/${wfile}
		echo "Section: metapackages" >> ./suite/${dist}/debian/${wfile}
		echo "Architecture: arm64" >> ./suite/${dist}/debian/${wfile}
		echo "Pre-Depends: linux-image-${latest_kernel}" >> ./suite/${dist}/debian/${wfile}
		echo "Depends: \${misc:Depends}, bbb.io-kernel-tasks (= \${source:Version})" >> ./suite/${dist}/debian/${wfile}
		echo "Description: BeagleBoard.org Mainline" >> ./suite/${dist}/debian/${wfile}
		echo " This metapackage will install Mainline in Debian." >> ./suite/${dist}/debian/${wfile}
	fi
}

generate_kernel_k3 () {
	if [ ! "x${latest_kernel}" = "x" ] ; then
		echo "" >> ./suite/${dist}/debian/${wfile}
		echo "Package: bbb.io-kernel-${msg}" >> ./suite/${dist}/debian/${wfile}
		echo "Section: metapackages" >> ./suite/${dist}/debian/${wfile}
		echo "Architecture: arm64" >> ./suite/${dist}/debian/${wfile}
		echo "Pre-Depends: linux-image-${latest_kernel}" >> ./suite/${dist}/debian/${wfile}
		echo "Depends: \${misc:Depends}, bbb.io-kernel-tasks (= \${source:Version})" >> ./suite/${dist}/debian/${wfile}
		echo "Description: BeagleBoard.org ${msg}-arm64 for k3-arm64" >> ./suite/${dist}/debian/${wfile}
		echo " This metapackage will install linux-image-${msg}-arm64 for in Debian." >> ./suite/${dist}/debian/${wfile}
	fi
}

changelog () {
	git diff ./suite/${dist}/debian/control > /tmp/changelog-readme.diff
	cat /tmp/changelog-readme.diff | grep +Pre-Depends: | awk '{print $2}' | awk -F ',' '{print $1}' > /tmp/changelog-readme.cat
	sort -u /tmp/changelog-readme.cat > /tmp/changelog-readme.sort
	echo "  * Kernel Updates" > suite/${dist}/readme.log
	ts "  *" /tmp/changelog-readme.sort >> suite/${dist}/readme.log
	cat suite/${dist}/readme.log
}

do_jammy () {
	#22.04
	arch="arm64"
	dist="jammy"
	debhelper="13"
	wfile="control"
	generate_header

	sgxam62="enabled"
	sgxj721e="enabled"
	sgxmodule="sgx-23.1"

	msg="5.10-ti"   ; var="ti-arm64" ; ver="LTS510"  ; current_kernel ; generate_kernel_ti
	msg="6.1-ti"    ; var="ti-arm64"    ; ver="LTS61"   ; current_kernel ; generate_kernel_ti
	msg="6.1-rt-ti" ; var="ti-rt-arm64" ; ver="LTS61"   ; current_kernel ; generate_kernel_ti

	unset sgxam62
	unset sgxj721e
	unset sgxmodule

	msg="mainline"  ; var="arm64"     ; ver="STABLE"  ; current_kernel ; generate_mainline_kernel
	msg="6.3-k3"    ; var="k3-arm64"    ; ver="V63X"  ; current_kernel ; generate_kernel_k3
	msg="6.3-rt-k3" ; var="k3-arm64-rt" ; ver="V63X"  ; current_kernel ; generate_kernel_k3
	msg="6.4-k3"    ; var="k3-arm64"    ; ver="V64X"  ; current_kernel ; generate_kernel_k3
	msg="6.4-rt-k3" ; var="k3-arm64-rt" ; ver="V64X"  ; current_kernel ; generate_kernel_k3
	msg="6.5-k3"    ; var="k3-arm64"    ; ver="V65X"  ; current_kernel ; generate_kernel_k3
	msg="6.5-rt-k3" ; var="k3-arm64-rt" ; ver="V65X"  ; current_kernel ; generate_kernel_k3
	msg="6.6-k3"    ; var="k3-arm64"    ; ver="LTS66" ; current_kernel ; generate_kernel_k3
	msg="6.6-rt-k3" ; var="k3-arm64-rt" ; ver="LTS66" ; current_kernel ; generate_kernel_k3
	msg="6.7-k3"    ; var="k3-arm64"    ; ver="V67X"  ; current_kernel ; generate_kernel_k3
	msg="6.8-k3"    ; var="k3-arm64"    ; ver="V68X"  ; current_kernel ; generate_kernel_k3
	changelog
}

do_noble () {
	#24.04
	arch="arm64"
	dist="noble"
	debhelper="13"
	wfile="control"
	generate_header

	sgxam62="enabled"
	sgxj721e="enabled"
	sgxmodule="sgx-23.1"

	msg="5.10-ti"   ; var="ti-arm64" ; ver="LTS510"  ; current_kernel ; generate_kernel_ti
	msg="6.1-ti"    ; var="ti-arm64"    ; ver="LTS61"   ; current_kernel ; generate_kernel_ti
	msg="6.1-rt-ti" ; var="ti-rt-arm64" ; ver="LTS61"   ; current_kernel ; generate_kernel_ti

	unset sgxam62
	unset sgxj721e
	unset sgxmodule

	msg="mainline"  ; var="arm64"     ; ver="STABLE"  ; current_kernel ; generate_mainline_kernel
	msg="6.3-k3"    ; var="k3-arm64"    ; ver="V63X"  ; current_kernel ; generate_kernel_k3
	msg="6.4-k3"    ; var="k3-arm64"    ; ver="V64X"  ; current_kernel ; generate_kernel_k3
	msg="6.5-k3"    ; var="k3-arm64"    ; ver="V65X"  ; current_kernel ; generate_kernel_k3
	msg="6.6-k3"    ; var="k3-arm64"    ; ver="LTS66" ; current_kernel ; generate_kernel_k3
	msg="6.6-rt-k3" ; var="k3-arm64-rt" ; ver="LTS66" ; current_kernel ; generate_kernel_k3
	msg="6.7-k3"    ; var="k3-arm64"    ; ver="V67X"  ; current_kernel ; generate_kernel_k3
	msg="6.8-k3"    ; var="k3-arm64"    ; ver="V68X"  ; current_kernel ; generate_kernel_k3

	changelog
}

do_bullseye () {
	#11.x
	arch="arm64"
	dist="bullseye"
	debhelper="13"
	wfile="control"
	generate_header

	sgxam62="enabled"
	sgxj721e="enabled"
	sgxmodule="sgx"

	msg="5.10-ti"   ; var="ti-arm64" ; ver="LTS510"  ; current_kernel ; generate_kernel_ti

	unset sgxam62
	unset sgxj721e
	unset sgxmodule

	msg="6.1-ti"    ; var="ti-arm64"    ; ver="LTS61"   ; current_kernel ; generate_kernel_ti
	msg="6.1-rt-ti" ; var="ti-rt-arm64" ; ver="LTS61"   ; current_kernel ; generate_kernel_ti

	msg="mainline"  ; var="arm64"     ; ver="STABLE"  ; current_kernel ; generate_mainline_kernel
	msg="6.3-k3"    ; var="k3-arm64"    ; ver="V63X"  ; current_kernel ; generate_kernel_k3
	msg="6.3-rt-k3" ; var="k3-arm64-rt" ; ver="V63X"  ; current_kernel ; generate_kernel_k3
	msg="6.4-k3"    ; var="k3-arm64"    ; ver="V64X"  ; current_kernel ; generate_kernel_k3
	msg="6.4-rt-k3" ; var="k3-arm64-rt" ; ver="V64X"  ; current_kernel ; generate_kernel_k3
	msg="6.5-k3"    ; var="k3-arm64"    ; ver="V65X"  ; current_kernel ; generate_kernel_k3
	msg="6.5-rt-k3" ; var="k3-arm64-rt" ; ver="V65X"  ; current_kernel ; generate_kernel_k3
	msg="6.6-k3"    ; var="k3-arm64"    ; ver="LTS66" ; current_kernel ; generate_kernel_k3
	msg="6.6-rt-k3" ; var="k3-arm64-rt" ; ver="LTS66" ; current_kernel ; generate_kernel_k3
	msg="6.7-k3"    ; var="k3-arm64"    ; ver="V67X"  ; current_kernel ; generate_kernel_k3
	msg="6.8-k3"    ; var="k3-arm64"    ; ver="V68X"  ; current_kernel ; generate_kernel_k3
	changelog
}

do_bookworm () {
	#12.x
	arch="arm64"
	dist="bookworm"
	debhelper="13"
	wfile="control"
	generate_header
	am62_dev="enabled"
	j721e_dev="enabled"

	sgxam62="enabled"
	sgxj721e="enabled"
	sgxmodule="sgx-23.1"

	msg="5.10-ti"   ; var="ti-arm64" ; ver="LTS510"  ; current_kernel ; generate_kernel_ti
	msg="6.1-ti"    ; var="ti-arm64"    ; ver="LTS61"   ; current_kernel ; generate_kernel_ti
	msg="6.1-rt-ti" ; var="ti-rt-arm64" ; ver="LTS61"   ; current_kernel ; generate_kernel_ti

	unset sgxam62
	unset sgxj721e
	unset sgxmodule

	unset am62_dev
	unset j721e_dev

	msg="mainline"  ; var="arm64"     ; ver="STABLE"  ; current_kernel ; generate_mainline_kernel
	msg="6.3-k3"    ; var="k3-arm64"    ; ver="V63X"  ; current_kernel ; generate_kernel_k3
	msg="6.3-rt-k3" ; var="k3-arm64-rt" ; ver="V63X"  ; current_kernel ; generate_kernel_k3
	msg="6.4-k3"    ; var="k3-arm64"    ; ver="V64X"  ; current_kernel ; generate_kernel_k3
	msg="6.4-rt-k3" ; var="k3-arm64-rt" ; ver="V64X"  ; current_kernel ; generate_kernel_k3
	msg="6.5-k3"    ; var="k3-arm64"    ; ver="V65X"  ; current_kernel ; generate_kernel_k3
	msg="6.5-rt-k3" ; var="k3-arm64-rt" ; ver="V65X"  ; current_kernel ; generate_kernel_k3
	msg="6.6-k3"    ; var="k3-arm64"    ; ver="LTS66" ; current_kernel ; generate_kernel_k3
	msg="6.6-rt-k3" ; var="k3-arm64-rt" ; ver="LTS66" ; current_kernel ; generate_kernel_k3
	msg="6.7-k3"    ; var="k3-arm64"    ; ver="V67X"  ; current_kernel ; generate_kernel_k3
	msg="6.8-k3"    ; var="k3-arm64"    ; ver="V68X"  ; current_kernel ; generate_kernel_k3
	changelog
}

do_trixie () {
	#13.x
	arch="arm64"
	dist="trixie"
	debhelper="13"
	wfile="control"
	generate_header

	sgxam62="enabled"
	sgxj721e="enabled"
	sgxmodule="sgx-23.1"

	msg="5.10-ti"   ; var="ti-arm64" ; ver="LTS510"  ; current_kernel ; generate_kernel_ti
	msg="6.1-ti"    ; var="ti-arm64"    ; ver="LTS61"   ; current_kernel ; generate_kernel_ti
	msg="6.1-rt-ti" ; var="ti-rt-arm64" ; ver="LTS61"   ; current_kernel ; generate_kernel_ti

	unset sgxam62
	unset sgxj721e
	unset sgxmodule

	msg="mainline"  ; var="arm64"     ; ver="STABLE"  ; current_kernel ; generate_mainline_kernel
	msg="6.3-k3"    ; var="k3-arm64"    ; ver="V63X"  ; current_kernel ; generate_kernel_k3
	msg="6.3-rt-k3" ; var="k3-arm64-rt" ; ver="V63X"  ; current_kernel ; generate_kernel_k3
	msg="6.4-k3"    ; var="k3-arm64"    ; ver="V64X"  ; current_kernel ; generate_kernel_k3
	msg="6.4-rt-k3" ; var="k3-arm64-rt" ; ver="V64X"  ; current_kernel ; generate_kernel_k3
	msg="6.5-k3"    ; var="k3-arm64"    ; ver="V65X"  ; current_kernel ; generate_kernel_k3
	msg="6.5-rt-k3" ; var="k3-arm64-rt" ; ver="V65X"  ; current_kernel ; generate_kernel_k3
	msg="6.6-k3"    ; var="k3-arm64"    ; ver="LTS66" ; current_kernel ; generate_kernel_k3
	msg="6.6-rt-k3" ; var="k3-arm64-rt" ; ver="LTS66" ; current_kernel ; generate_kernel_k3
	msg="6.7-k3"    ; var="k3-arm64"    ; ver="V67X"  ; current_kernel ; generate_kernel_k3
	msg="6.8-k3"    ; var="k3-arm64"    ; ver="V68X"  ; current_kernel ; generate_kernel_k3
	changelog
}

do_jammy
do_noble
do_bullseye
do_bookworm
do_trixie

